services:
  app:
    build:
      context: .
    container_name: omega-web-server
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    container_name: omega-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: godoka
      MONGO_INITDB_ROOT_PASSWORD: HpUKQ3Zel7JyRg7eYl3ZqlI47
      MONGO_DB_NAME: omega

volumes:
  mongo_data:
