version: "3.9"
services:
  app:
    image: node:18
    container_name: omega-web-server
    working_dir: /
    volumes:
      - /data/compose/9:/app:rw
    ports:
      - "3000:3000"
    command: ["npm", "start"]
