version: "3.9"
services:
  app:
    image: node:22
    container_name: omega-web-server
    working_dir: /app  # Define o diretório de trabalho dentro do contêiner
    volumes:
      - ./:/app  # Substitua './app' pelo caminho correto para seu código no host
    ports:
      - "3000:3000"
    command: ["npm", "start"]
