version: "3.9"

services:
  omega-web-server:
    build:
      context: .  # Diretório onde o Dockerfile está localizado
    container_name: omega-web-server
    ports:
      - "3000:3000"  # Mapear a porta interna do contêiner para a porta do host
    volumes:
      - .:/app  # Montar o diretório da aplicação no host para o contêiner
    environment:
      - NODE_ENV=production
