FROM node:22

RUN apt-get update && apt-get install -y \
  build-essential \
  python3 \
  make \
  g++

WORKDIR /app

COPY package.json /app/

ARG MONGO_INITDB_ROOT_USERNAME
ARG MONGO_INITDB_ROOT_PASSWORD
ARG MONGO_DB_NAME

ENV MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
ENV MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
ENV MONGO_DB_NAME=$MONGO_DB_NAME

RUN yarn install

COPY . /app
COPY .env .env

EXPOSE 3000
EXPOSE 3001

CMD ["yarn", "start"]
