services:
  app:
    build:
      context: .
    container_name: omega-web-server
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
