services:
  omega-web-server:
    build:
      context: .  # Diretório onde o Dockerfile está localizado
    container_name: omega-web-server
    ports:
      - "3000:3000"  # Mapeia a porta do contêiner para a do host
    volumes:
      - .:/app  # Monta o diretório atual da aplicação no contêiner
    working_dir: /app  # Define o diretório de trabalho como /app
    environment:
      - NODE_ENV=production
