import sqlite3 from 'sqlite3';
sqlite3.verbose();

const weight = {
  handtrap: 1,
  tech: 1,
  engine: 2,
  deck: 3,
  subdeck: 0,
}

const db = new sqlite3.Database("./omega.db", (err) => {
  if (err) {
    reject('Erro ao conectar ao banco de dados: ' + err.message);
  }
});

export const sets = [
  { code: 0x1, set: "Ally of Justice" },
  { code: 0x2, set: "Genex" },
  { code: 0x1002, set: "R-Genex" },
  { code: 0x2002, set: "Genex Ally" },
  { code: 0x3, set: "Allure Queen" },
  { code: 0x4, set: "Amazoness" },
  { code: 0x5, set: "Arcana Force" },
  { code: 0x6, set: "Dark World" },
  { code: 0x7, set: "Ancient Gear" },
  { code: 0x8, set: "HERO" },
  { code: 0x3008, set: "Elemental HERO" },
  { code: 0x6008, set: "Evil HERO" },
  { code: 0xc008, set: "Destiny HERO" },
  { code: 0x5008, set: "Vision HERO" },
  { code: 0xa008, set: "Masked HERO" },
  { code: 0x9, set: "Neos" },
  { code: 0xa, set: "Lswarm" },
  { code: 0x100a, set: "Steelswarm" },
  { code: 0xb, set: "Infernity" },
  { code: 0xc, set: "Alien" },
  { code: 0xd, set: "Saber" },
  { code: 0x100d, set: "X-Saber" },
  { code: 0x300d, set: "XX-Saber" },
  { code: 0x400d, set: "Elementsaber" },
  { code: 0xe, set: "Watt" },
  { code: 0xf, set: "Ojama" },
  { code: 0x10, set: "Gusto" },
  { code: 0x11, set: "Karakuri" },
  { code: 0x12, set: "Frog" },
  { code: 0x13, set: "Meklord" },
  { code: 0x3013, set: "Meklord Emperor" },
  { code: 0x5013, set: "Meklord Astro" },
  { code: 0x6013, set: "Meklord Army" },
  { code: 0x15, set: "B.E.S." },
  { code: 0x16, set: "Roid" },
  { code: 0x1016, set: "Vehicroid" },
  { code: 0x2016, set: "Speedroid" },
  { code: 0x17, set: "Synchro" },
  { code: 0x1017, set: "Synchron" },
  { code: 0x2017, set: "Synchro Dragon" },
  { code: 0x18, set: "Cloudian" },
  { code: 0x19, set: "Gladiator" },
  { code: 0x1019, set: "Gladiator Beast" },
  { code: 0x1a, set: "Dark Scorpion" },
  { code: 0x1b, set: "Phantom Beast" },
  { code: 0x101b, set: "Mecha Phantom Beast" },
  { code: 0x1c, set: "Spirit Message" },
  { code: 0x1d, set: "Koa'ki Meiru" },
  { code: 0x1e, set: "Chrysalis" },
  { code: 0x1f, set: "Neo-Spacian" },
  { code: 0x20, set: "Shien" },
  { code: 0x21, set: "Earthbound" },
  { code: 0x1021, set: "Earthbound Immortal" },
  { code: 0x22, set: "Jurrac" },
  { code: 0x23, set: "Malefic" },
  { code: 0x24, set: "Scrap" },
  { code: 0x25, set: "Iron Chain" },
  { code: 0x26, set: "Morphtronic" },
  { code: 0x27, set: "T.G." },
  { code: 0x28, set: "Batteryman" },
  { code: 0x29, set: "Dragunity" },
  { code: 0x2a, set: "Naturia" },
  { code: 0x2b, set: "Ninja" },
  { code: 0x102b, set: "Armor Ninja" },
  { code: 0x2c, set: "Flamvell" },
  { code: 0x2e, set: "Gravekeeper's" },
  { code: 0x2f, set: "Ice Barrier" },
  { code: 0x30, set: "Vylon" },
  { code: 0x31, set: "Fortune Lady" },
  { code: 0x32, set: "Volcanic" },
  { code: 0x33, set: "Blackwing" },
  { code: 0x1033, set: "Assault Blackwing" },
  { code: 0x34, set: "Crystal" },
  { code: 0x1034, set: "Crystal Beast" },
  { code: 0x2034, set: "Ultimate Crystal" },
  { code: 0x5034, set: "Advanced Crystal Beast" },
  { code: 0x35, set: "Fabled" },
  { code: 0x1035, set: "The Fabled" },
  { code: 0x36, set: "Machina" },
  { code: 0x37, set: "Mist Valley" },
  { code: 0x38, set: "Lightsworn" },
  { code: 0x39, set: "Laval" },
  { code: 0x3a, set: "Gishki" },
  { code: 0x3b, set: "Red-Eyes" },
  { code: 0x3c, set: "Reptilianne" },
  { code: 0x103d, set: "Six Samurai" },
  { code: 0x203d, set: "Six Strike" },
  { code: 0x903d, set: "Secret Six Samurai" },
  { code: 0x3e, set: "Worm" },
  { code: 0x3f, set: "Majestic" },
  { code: 0x40, set: "Forbidden One" },
  { code: 0x41, set: "LV" },
  { code: 0x42, set: "Nordic" },
  { code: 0x3042, set: "Nordic Ascendant" },
  { code: 0x6042, set: "Nordic Beast" },
  { code: 0xa042, set: "Nordic Alfar" },
  { code: 0x5042, set: "Nordic Relic" },
  { code: 0x43, set: "Junk" },
  { code: 0x44, set: "The Agent" },
  { code: 0x45, set: "Archfiend" },
  { code: 0x1045, set: "Red Dragon Archfiend" },
  { code: 0x46, set: "Polymerization" },
  { code: 0x46, set: "Fusion" },
  { code: 0x1046, set: "Fusion Dragon" },
  { code: 0x47, set: "Gem-" },
  { code: 0x1047, set: "Gem-Knight" },
  { code: 0x48, set: "Number" },
  { code: 0x1048, set: "Number C" },
  { code: 0x5048, set: "Number C39" },
  { code: 0x49, set: "Skyblaster" },
  { code: 0x4a, set: "Timelord" },
  { code: 0x4b, set: "Aesir" },
  { code: 0x4c, set: "Trap Hole" },
  { code: 0x4e, set: "Evol" },
  { code: 0x304e, set: "Evoltile" },
  { code: 0x504e, set: "Evolzar" },
  { code: 0x604e, set: "Evolsaur" },
  { code: 0x4f, set: "Buster" },
  { code: 0x104f, set: "/Assault Mode" },
  { code: 0x50, set: "Venom" },
  { code: 0x1050, set: "Starving Venom" },
  { code: 0x51, set: "Gadget" },
  { code: 0x52, set: "Guardian" },
  { code: 0x1052, set: "Gate Guardian" },
  { code: 0x2052, set: "Skull Guardian" },
  { code: 0x53, set: "Constellar" },
  { code: 0x54, set: "Gagaga" },
  { code: 0x55, set: "Photon" },
  { code: 0x56, set: "Inzektor" },
  { code: 0x57, set: "Resonator" },
  { code: 0x58, set: "Wind-Up" },
  { code: 0x59, set: "Gogogo" },
  { code: 0x5a, set: "Penguin" },
  { code: 0x5b, set: "Inmato" },
  { code: 0x5c, set: "Sphinx" },
  { code: 0x60, set: "Bamboo Sword" },
  { code: 0x61, set: "Ninjitsu Art" },
  { code: 0x62, set: "Toon" },
  { code: 0x63, set: "Reactor" },
  { code: 0x64, set: "Harpie" },
  { code: 0x65, set: "Infestation" },
  { code: 0x66, set: "Warrior" },
  { code: 0x1066, set: "Symphonic Warrior" },
  { code: 0x2066, set: "Magnet Warrior" },
  { code: 0x67, set: "Iron" },
  { code: 0x68, set: "Tin" },
  { code: 0x69, set: "Hieratic" },
  { code: 0x6a, set: "Butterspy" },
  { code: 0x6b, set: "Bounzer" },
  { code: 0x6c, set: "Lightray" },
  { code: 0x6d, set: "Djinn" },
  { code: 0x306d, set: "Divine Dragon" },
  { code: 0x606d, set: "Djinn of Rituals" },
  { code: 0x6e, set: "Prophecy" },
  { code: 0x106e, set: "Spellbook" },
  { code: 0x6f, set: "Heroic" },
  { code: 0x106f, set: "Heroic Challenger" },
  { code: 0x70, set: "Chronomaly" },
  { code: 0x71, set: "Madolche" },
  { code: 0x72, set: "Geargia" },
  { code: 0x1072, set: "Geargiano" },
  { code: 0x73, set: "Xyz" },
  { code: 0x1073, set: "CXyz" },
  { code: 0x2073, set: "Xyz Dragon" },
  { code: 0x4073, set: "Armored Xyz" },
  { code: 0x74, set: "Mermail" },
  { code: 0x75, set: "Abyss-" },
  { code: 0x76, set: "Heraldic Beast" },
  { code: 0x77, set: "Atlantean" },
  { code: 0x78, set: "Nimble" },
  { code: 0x79, set: "Fire Fist" },
  { code: 0x7a, set: "Noble" },
  { code: 0x107a, set: "Noble Knight" },
  { code: 0x207a, set: "Noble Arms" },
  { code: 0x507a, set: "Infernoble Knight" },
  { code: 0x607a, set: "Infernoble Arms" },
  { code: 0x7b, set: "Galaxy" },
  { code: 0x107b, set: "Galaxy-Eyes" },
  { code: 0x307b, set: "Galaxy-Eyes Tachyon Dragon" },
  { code: 0x7c, set: "Fire Formation" },
  { code: 0x7d, set: "Hazy" },
  { code: 0x107d, set: "Hazy Flame" },
  { code: 0x7e, set: "ZEXAL" },
  { code: 0x207e, set: "ZS -" },
  { code: 0x107e, set: "ZW -" },
  { code: 0x7f, set: "Utopi" },
  { code: 0x107f, set: "Utopia" },
  { code: 0x207f, set: "Utopic Future" },
  { code: 0x80, set: "Duston" },
  { code: 0x81, set: "Fire King" },
  { code: 0x1081, set: "Fire King Avatar" },
  { code: 0x82, set: "Dododo" },
  { code: 0x83, set: "Puppet" },
  { code: 0x1083, set: "Gimmick Puppet" },
  { code: 0x84, set: "Battlin' Box" },
  { code: 0x1084, set: "Battlin' Boxer" },
  { code: 0x2084, set: "Battlin' Boxing" },
  { code: 0x85, set: "Super Defense Robot" },
  { code: 0x86, set: "Star Seraph" },
  { code: 0x87, set: "Umbral Horror" },
  { code: 0x88, set: "Bujin" },
  { code: 0x89, set: "Hole" },
  { code: 0x8a, set: "Fascinating" },
  { code: 0x108a, set: "Traptrix" },
  { code: 0x8b, set: "Malicevorous" },
  { code: 0x8d, set: "Ghostrick" },
  { code: 0x8e, set: "Vampire" },
  { code: 0x8f, set: "Zubaba" },
  { code: 0x90, set: "Sylvan" },
  { code: 0x91, set: "Necrovalley" },
  { code: 0x92, set: "Heraldry" },
  { code: 0x93, set: "Cyber" },
  { code: 0x1093, set: "Cyber Dragon" },
  { code: 0x2093, set: "Cyber Angel" },
  { code: 0x4093, set: "Cyberdark" },
  { code: 0x94, set: "Cybernetic" },
  { code: 0x95, set: "Rank-Up-Magic" },
  { code: 0x96, set: "Fishborg" },
  { code: 0x97, set: "Artifact" },
  { code: 0x98, set: "Magician" },
  { code: 0x99, set: "Odd-Eyes" },
  { code: 0x9a, set: "Superheavy Samurai" },
  { code: 0x109a, set: "Superheavy Samurai Soul" },
  { code: 0x9b, set: "Melodious" },
  { code: 0x109b, set: "Melodious Maestra" },
  { code: 0x9c, set: "tellarknight" },
  { code: 0x109c, set: "Stellarknight" },
  { code: 0x9d, set: "Shaddoll" },
  { code: 0x9e, set: "Yang Zing" },
  { code: 0x9f, set: "Performapal" },
  { code: 0xa0, set: "Legendary Knight" },
  { code: 0xa1, set: "Legendary Dragon" },
  { code: 0x10a2, set: "Dark Magician" },
  { code: 0x20a2, set: "Magician Girl" },
  { code: 0x30a2, set: "Dark Magician Girl" },
  { code: 0xa3, set: "Stardust" },
  { code: 0xa4, set: "Kuriboh" },
  { code: 0x10a4, set: "Winged Kuriboh" },
  { code: 0xa5, set: "Change" },
  { code: 0xa6, set: "Sprout" },
  { code: 0xa7, set: "Artorigus" },
  { code: 0xa8, set: "Laundsallyn" },
  { code: 0xa9, set: "Fluffal" },
  { code: 0xaa, set: "Qli" },
  { code: 0x10aa, set: "Apoqliphort" },
  { code: 0xab, set: "Deskbot" },
  { code: 0xac, set: "Goblin" },
  { code: 0x10ac, set: "Goblin Biker" },
  { code: 0xad, set: "Frightfur" },
  { code: 0xae, set: "Dark Contract" },
  { code: 0xaf, set: "D/D" },
  { code: 0x10af, set: "D/D/D" },
  { code: 0xb0, set: "Gottoms" },
  { code: 0xb1, set: "Burning Abyss" },
  { code: 0xb2, set: "U.A." },
  { code: 0xb3, set: "Yosenju" },
  { code: 0xb4, set: "Nekroz" },
  { code: 0xb5, set: "Ritual Beast" },
  { code: 0x10b5, set: "Ritual Beast Tamer" },
  { code: 0x20b5, set: "Spiritual Beast" },
  { code: 0x40b5, set: "Ritual Beast Ulti" },
  { code: 0xb6, set: "Outer Entity" },
  { code: 0xb7, set: "Elder Entity" },
  { code: 0xb8, set: "Old Entity" },
  { code: 0xb9, set: "Blaze Accelerator" },
  { code: 0xba, set: "Raidraptor" },
  { code: 0xbb, set: "Infernoid" },
  { code: 0xbc, set: "Jinzo" },
  { code: 0xbd, set: "Gaia The Fierce Knight" },
  { code: 0xbe, set: "Monarch" },
  { code: 0xbf, set: "Charmer" },
  { code: 0xc0, set: "Possessed" },
  { code: 0x10c0, set: "Familiar-Possessed" },
  { code: 0xc1, set: "PSY-Frame" },
  { code: 0x10c1, set: "PSY-Framegear" },
  { code: 0xc2, set: "Power Tool" },
  { code: 0xc3, set: "Edge Imp" },
  { code: 0xc4, set: "Zefra" },
  { code: 0xc5, set: "Void" },
  { code: 0xc6, set: "Performage" },
  { code: 0xc7, set: "Dracoslayer" },
  { code: 0xc8, set: "Igknight" },
  { code: 0xc9, set: "Aroma" },
  { code: 0xca, set: "Empowered Warrior" },
  { code: 0xcb, set: "Aether" },
  { code: 0xcc, set: "Prediction Princess" },
  { code: 0xcd, set: "Aquaactress" },
  { code: 0xce, set: "Aquarium" },
  { code: 0xcf, set: "Chaos" },
  { code: 0x10cf, set: "Black Luster Soldier" },
  { code: 0xd0, set: "Majespecter" },
  { code: 0xd1, set: "Graydle" },
  { code: 0xd2, set: "Kozmo" },
  { code: 0xd3, set: "Kaiju" },
  { code: 0xd4, set: "Paleozoic" },
  { code: 0xd5, set: "Dante" },
  { code: 0xd6, set: "Destruction Sword" },
  { code: 0xd7, set: "Buster Blader" },
  { code: 0xd8, set: "Dinomist" },
  { code: 0xd9, set: "Shiranui" },
  { code: 0x10d9, set: "Shiranui Spectralsword" },
  { code: 0xda, set: "Dracoverlord" },
  { code: 0xdb, set: "Phantom Knights" },
  { code: 0x10db, set: "The Phantom Knights" },
  { code: 0xdc, set: "Super Quant" },
  { code: 0x10dc, set: "Super Quantum" },
  { code: 0x20dc, set: "Super Quantal Mech Beast" },
  { code: 0xdd, set: "Blue-Eyes" },
  { code: 0xde, set: "Exodia" },
  { code: 0xdf, set: "Lunalight" },
  { code: 0xe0, set: "Amorphage" },
  { code: 0xe1, set: "Metalfoes" },
  { code: 0xe2, set: "Triamid" },
  { code: 0xe3, set: "Cubic" },
  { code: 0xe4, set: "Celtic Guard" },
  { code: 0xe5, set: "Cipher" },
  { code: 0x10e5, set: "Cipher Dragon" },
  { code: 0xe6, set: "Flower Cardian" },
  { code: 0xe7, set: "Silent Swordsman" },
  { code: 0xe8, set: "Silent Magician" },
  { code: 0xe9, set: "Magna Warrior" },
  { code: 0xea, set: "Crystron" },
  { code: 0xeb, set: "Chemicritter" },
  { code: 0xec, set: "Abyss" },
  { code: 0x10ec, set: "Abyss Actor" },
  { code: 0x20ec, set: "Abyss Script" },
  { code: 0xed, set: "Subterror" },
  { code: 0x10ed, set: "Subterror Behemoth" },
  { code: 0xee, set: "SPYRAL" },
  { code: 0x10ee, set: "SPYRAL GEAR" },
  { code: 0x20ee, set: "SPYRAL MISSION" },
  { code: 0xef, set: "Darklord" },
  { code: 0xf0, set: "Windwitch" },
  { code: 0xf1, set: "Zoodiac" },
  { code: 0xf2, set: "Pendulum" },
  { code: 0x10f2, set: "Pendulum Dragon" },
  { code: 0x20f2, set: "Pendulumgraph" },
  { code: 0xf3, set: "Predap" },
  { code: 0x10f3, set: "Predaplant" },
  { code: 0xf4, set: "Invoked" },
  { code: 0xf5, set: "Gandora" },
  { code: 0xf6, set: "Skyscraper" },
  { code: 0xf7, set: "Lyrilusc" },
  { code: 0xf8, set: "Supreme King" },
  { code: 0x10f8, set: "Supreme King Gate" },
  { code: 0x20f8, set: "Supreme King Dragon" },
  { code: 0xf9, set: "True King" },
  { code: 0xf9, set: "True Draco" },
  { code: 0xfa, set: "Phantasm Spiral" },
  { code: 0xfb, set: "Trickstar" },
  { code: 0xfc, set: "Gouki" },
  { code: 0xfd, set: "World Chalice" },
  { code: 0xfe, set: "World Legacy" },
  { code: 0xff, set: "Clear Wing" },
  { code: 0x100, set: "Bonding" },
  { code: 0x101, set: "code Talker" },
  { code: 0x102, set: "rokket" },
  { code: 0x103, set: "Altergeist" },
  { code: 0x104, set: "Krawler" },
  { code: 0x105, set: "Metaphys" },
  { code: 0x106, set: "Vendread" },
  { code: 0x107, set: "F.A." },
  { code: 0x108, set: "Magical Musket" },
  { code: 0x109, set: "The Weather" },
  { code: 0x10a, set: "Parshath" },
  { code: 0x10b, set: "Tindangle" },
  { code: 0x10c, set: "Mekk-Knight" },
  { code: 0x10d, set: "Mythical Beast" },
  { code: 0x10e, set: "Evolution Pill" },
  { code: 0x10f, set: "Borrel" },
  { code: 0x110, set: "Relinquished" },
  { code: 0x1110, set: "Eyes Restrict" },
  { code: 0x111, set: "Armed Dragon" },
  { code: 0x112, set: "Knightmare" },
  { code: 0x113, set: "Elemental Lord" },
  { code: 0x114, set: "Fur Hire" },
  { code: 0x115, set: "Sky Striker" },
  { code: 0x1115, set: "Sky Striker Ace" },
  { code: 0x116, set: "Crusadia" },
  { code: 0x117, set: "Impcantation" },
  { code: 0x118, set: "Cynet" },
  { code: 0x119, set: "Salamangreat" },
  { code: 0x11a, set: "Dinowrestler" },
  { code: 0x11b, set: "Orcust" },
  { code: 0x11c, set: "Thunder Dragon" },
  { code: 0x11d, set: "Forbidden" },
  { code: 0x11e, set: "Danger!" },
  { code: 0x11f, set: "Nephthys" },
  { code: 0x120, set: "Prank-Kids" },
  { code: 0x121, set: "Mayakashi" },
  { code: 0x122, set: "Valkyrie" },
  { code: 0x123, set: "Rose" },
  { code: 0x1123, set: "Rose Dragon" },
  { code: 0x124, set: "Machine Angel" },
  { code: 0x125, set: "Smile" },
  { code: 0x126, set: "Time Thief" },
  { code: 0x127, set: "Infinitrack" },
  { code: 0x128, set: "Witchcrafter" },
  { code: 0x129, set: "Evil Eye" },
  { code: 0x12a, set: "Endymion" },
  { code: 0x12b, set: "Marincess" },
  { code: 0x12c, set: "Tenyi" },
  { code: 0x12d, set: "Simorgh" },
  { code: 0x12e, set: "Fortune Fairy" },
  { code: 0x12f, set: "Battlewasp" },
  { code: 0x130, set: "Unchained" },
  { code: 0x1130, set: "Unchained Soul" },
  { code: 0x131, set: "Dream Mirror" },
  { code: 0x132, set: "Mathmech" },
  { code: 0x133, set: "Dragonmaid" },
  { code: 0x134, set: "Generaider" },
  { code: 0x135, set: "@Ignister" },
  { code: 0x136, set: "A.I." },
  { code: 0x137, set: "Ancient Warriors" },
  { code: 0x138, set: "Megalith" },
  { code: 0x139, set: "Palladium" },
  { code: 0x13a, set: "Onomat" },
  { code: 0x13b, set: "Rebellion" },
  { code: 0x13c, set: "Codebreaker" },
  { code: 0x13d, set: "Nemeses" },
  { code: 0x13e, set: "Barbaros" },
  { code: 0x13f, set: "Plunder Patroll" },
  { code: 0x140, set: "Adamancipator" },
  { code: 0x141, set: "Rikka" },
  { code: 0x142, set: "Eld" },
  { code: 0x1142, set: "Eldlich" },
  { code: 0x2142, set: "Eldlixir" },
  { code: 0x143, set: "Golden Land" },
  { code: 0x144, set: "Phantasm" },
  { code: 0x145, set: "Dogmatika" },
  { code: 0x146, set: "Melffy" },
  { code: 0x147, set: "Potan" },
  { code: 0x148, set: "Roland" },
  { code: 0x149, set: "Fossil" },
  { code: 0x14a, set: "Numeron" },
  { code: 0x114a, set: "Numeron Gate" },
  { code: 0x14b, set: "Appliancer" },
  { code: 0x14c, set: "Spiritual Art" },
  { code: 0x314c, set: "Spiritual Earth Art" },
  { code: 0x514c, set: "Spiritual Water Art" },
  { code: 0x614c, set: "Spiritual Fire Art" },
  { code: 0x914c, set: "Spiritual Wind Art" },
  { code: 0xa14c, set: "Spiritual Light Art" },
  { code: 0xc14c, set: "Dark Spirit Art" },
  { code: 0x14d, set: "Tri-Brigade" },
  { code: 0x14e, set: "Virtual World" },
  { code: 0x114e, set: "Virtual World Gate" },
  { code: 0x14f, set: "Dual Avatar" },
  { code: 0x150, set: "Magistus" },
  { code: 0x151, set: "Twin" },
  { code: 0x1151, set: "Live☆Twin" },
  { code: 0x2151, set: "Evil★Twin" },
  { code: 0x152, set: "Ki-sikil" },
  { code: 0x153, set: "Lil-la" },
  { code: 0x154, set: "Drytron" },
  { code: 0x155, set: "Springans" },
  { code: 0x156, set: "S-Force" },
  { code: 0x157, set: "Myutant" },
  { code: 0x158, set: "サン" },
  { code: 0x1158, set: "Sunvine" },
  { code: 0x2158, set: "Sunavalon" },
  { code: 0x4158, set: "Sunseed" },
  { code: 0x159, set: "Starry Knight" },
  { code: 0x15a, set: "Doll Monster" },
  { code: 0x15b, set: "Amazement" },
  { code: 0x15c, set: "Attraction" },
  { code: 0x15d, set: "Branded" },
  { code: 0x15e, set: "Rank-Down-Magic" },
  { code: 0x15f, set: "War Rock" },
  { code: 0x160, set: "Materiactor" },
  { code: 0x161, set: "Ogdoadic" },
  { code: 0x162, set: "Solfachord" },
  { code: 0x1162, set: "GranSolfachord" },
  { code: 0x163, set: "Ursarctic" },
  { code: 0x164, set: "Despia" },
  { code: 0x165, set: "Magikey" },
  { code: 0x166, set: "Gunkan" },
  { code: 0x1167, set: "Mystical Beast of the Forest" },
  { code: 0x2167, set: "Mystical Spirit of the Forest" },
  { code: 0x168, set: "Stealth Kragen" },
  { code: 0x169, set: "Numerounius" },
  { code: 0x16a, set: "Number" },
  { code: 0x16b, set: "Swordsoul" },
  { code: 0x16c, set: "Icejade" },
  { code: 0x16d, set: "Floowandereeze" },
  { code: 0x16e, set: "Topologic" },
  { code: 0x16f, set: "Hyperion" },
  { code: 0x170, set: "Beetrooper" },
  { code: 0x171, set: "P.U.N.K." },
  { code: 0x172, set: "Exosister" },
  { code: 0x173, set: "Dinomorphia" },
  { code: 0x174, set: "Lady of Lament" },
  { code: 0x175, set: "Seventh" },
  { code: 0x176, set: "Barian's" },
  { code: 0x177, set: "Kairyu-Shin" },
  { code: 0x178, set: "Sea Stealth" },
  { code: 0x179, set: "Therion" },
  { code: 0x17a, set: "Scareclaw" },
  { code: 0x17b, set: "Battleguard" },
  { code: 0x17c, set: "Libromancer" },
  { code: 0x17d, set: "Vaylantz" },
  { code: 0x17e, set: "Labrynth" },
  { code: 0x117e, set: "Welcome Labrynth" },
  { code: 0x17f, set: "Runick" },
  { code: 0x180, set: "Spright" },
  { code: 0x181, set: "Tearlaments" },
  { code: 0x182, set: "Vernusylph" },
  { code: 0x183, set: "Mokey Mokey" },
  { code: 0x184, set: "Wingman" },
  { code: 0x185, set: "Doodle" },
  { code: 0x1185, set: "Doodle Beast" },
  { code: 0x2185, set: "Doodlebook" },
  { code: 0x186, set: "G Golem" },
  { code: 0x187, set: "Rainbow Bridge" },
  { code: 0x188, set: "Bystial" },
  { code: 0x189, set: "Kashtira" },
  { code: 0x18a, set: "Ghoti" },
  { code: 0x18b, set: "Rescue-ACE" },
  { code: 0x18c, set: "Purrely" },
  { code: 0x18d, set: "Mikanko" },
  { code: 0x18e, set: "Aquamirror" },
  { code: 0x18f, set: "Firewall" },
  { code: 0x190, set: "Mannadium" },
  { code: 0x191, set: "Nemleria" },
  { code: 0x192, set: "Gold Pride" },
  { code: 0x193, set: "Labyrinth Wall" },
  { code: 0x194, set: "Favorite" },
  { code: 0x195, set: "Vanquish Soul" },
  { code: 0x196, set: "Nouvelles" },
  { code: 0x197, set: "Recipe" },
  { code: 0x198, set: "Visas" },
  { code: 0x199, set: "Counter" },
  { code: 0x19a, set: "Veda" },
  { code: 0x19b, set: "Diabell" },
  { code: 0x119b, set: "Diabellstar" },
  { code: 0x19c, set: "Snake-Eye" },
  { code: 0x19d, set: "Horus" },
  { code: 0x119d, set: "Horus the Black Flame Dragon" },
  { code: 0x19e, set: "Sinful Spoils" },
  { code: 0x19f, set: "Patissciel" },
  { code: 0x1a0, set: "Heart" },
  { code: 0x1a1, set: "Memento" },
  { code: 0x1a2, set: "Centur-Ion" },
  { code: 0x1a3, set: "Vaalmonica" },
  { code: 0x1a4, set: "Tistina" },
  { code: 0x1a5, set: "Yubel" },
  { code: 0x1a6, set: "Voiceless Voice" },
  { code: 0x1a7, set: "White Aura" },
  { code: 0x1a8, set: "Toy" },
  { code: 0x1a9, set: "Sangen" },
  { code: 0x1aa, set: "Tenpai Dragon" },
  { code: 0x1ab, set: "Ragnaraika" },
  { code: 0x1ac, set: "Salamandra" },
  { code: 0x1ad, set: "Ashened" },
  { code: 0x1ae, set: "Millennium" },
  { code: 0x1af, set: "Exodd" },
  { code: 0x1b0, set: "Fiendsmith" },
  { code: 0x1b1, set: "White Forest" },
  { code: 0x1b2, set: "Mulcharmy" },
  { code: 0x1b3, set: "Emblema" },
  { code: 0x1b4, set: "Tachyon" },
  { code: 0x1b5, set: "Blue Tears" },
  { code: 0x1b6, set: "Wedju" },
  { code: 0x1b7, set: "Mimighoul" },
  { code: 0x1b8, set: "Shark" },
  { code: 0x11b8, set: "Shark Drake" },
  { code: 0x1b9, set: "Primite" },
  { code: 0x1ba, set: "Metalmorph" },
  { code: 0x1bb, set: "Morganite" },
  { code: 0x1bc, set: "Azamina" },
  { code: 0x1bd, set: "Schoolwork" },
  { code: 0x1be, set: "Ryzeal" },
  { code: 0x1bf, set: "Maliss" },
  { code: 0x1c0, set: "Ryu-Ge" },
  { code: 0x1c1, set: "Argostars" },
  { code: 0x1c2, set: "Aqua Jet" },
  { code: 0x2c3, set: "Dragon Ruler" },
  { code: 0x2c4, set: "Mitsurugi" },
  { code: 0x2c5, set: "Regenesis" },
  { code: 0x2c6, set: "Dominus" },
]

export const decodeDeck = async (passwords) => {
  const sql = `SELECT x.id, x.alias, x.setcode FROM datas x WHERE id IN (${passwords.join(',')})`;

  const data = await (new Promise((resolve, reject) => {
    db.all(sql, [], (err, rows) => {
      if (err) reject(err);
      resolve(rows);
    });
  }));


  const blobMap = passwords.map(c => data.find(({ id }) => id === c).setcode)
  const setMap =  blobMap.map(blob => {
    if (!blob) return 0;
    const reversedBlob = [...blob].reverse();
    const numbers = [];
    for (let i = 0; i < reversedBlob.length; i += 2) {
      const c = (reversedBlob[i] << 8) | (reversedBlob[i + 1] || 0)
      const set = sets.find(s => s.code === c)
      numbers.push(set);
    }
    
    return numbers
  })
  return setMap.flat().filter(Boolean)
};
